#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
docs="$root/docs"
output="$docs/INDEX.md"
mkdir -p "$docs"
# The script resolves docs/ next to its own parent directory, so a local-only
# install (.local/scripts/docs-index.sh) indexes .local/docs automatically.
case "$root" in
	*/.local) self='.local/scripts/docs-index.sh' toml="$root/project-kit.toml" ;;
	*) self='scripts/docs-index.sh' toml="$root/.local/project-kit.toml" ;;
esac
# A workspace root (install.sh --workspace) lists its member repositories.
workspace=false
if [[ -f "$toml" ]] && grep -qE '^[[:space:]]*mode[[:space:]]*=[[:space:]]*"workspace"' "$toml"; then
	workspace=true
fi

title_for() {
	# BSD sed has no \| alternation, so strip each known prefix separately and
	# fall back to removing a bare heading marker.
	sed -n '1{s/^# PRD [0-9][0-9][0-9][0-9] [—-] //; s/^# ADR [0-9][0-9][0-9][0-9] [—-] //; s/^# RFC [0-9][0-9][0-9][0-9] [—-] //; s/^# Research [—-] //; s/^# PRD [—-] //; s/^# //; p;}' "$1"
}

status_for() {
	# The first non-empty line under the record's "## Status". Markdown
	# links are stripped to their label: the line is rendered in the index,
	# where links relative to the record's own file would not resolve.
	awk '
		$0 == "## Status" { in_status = 1; next }
		in_status && NF { print; exit }
	' "$1" | sed 's/\[\([^]]*\)\]([^)]*)/\1/g'
}

write_rows() {
	local dir="$1"
	local kind="$2"
	local file name title status
	shopt -s nullglob
	for file in "$dir"/[0-9][0-9][0-9][0-9]-*.md; do
		name="${file##*/}"
		title="$(title_for "$file")"
		status="$(status_for "$file")"
		printf '| [%s](%s/%s) | %s | %s |\n' "${name%%-*}" "$kind" "$name" "${title:-$name}" "${status:--}"
	done
}

# Reports are dated records with a Status section, so they get their own
# writer: date-named files plus the status column write_rows reads.
write_report_rows() {
	local dir="$1"
	local kind="$2"
	local file name title status
	shopt -s nullglob
	for file in "$dir"/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-*.md; do
		name="${file##*/}"
		title="$(sed -n '1{s/^# Bug [—-] //; s/^# Investigation [—-] //; s/^# Postmortem [—-] //; s/^# //; p;}' "$file")"
		status="$(status_for "$file")"
		printf '| [%s](%s/%s) | %s | %s |\n' "$name" "$kind" "$name" "${title:-$name}" "${status:--}"
	done
}

write_document_rows() {
	local dir="$1"
	local kind="$2"
	local file name title
	shopt -s nullglob
	for file in "$dir"/*.md; do
		name="${file##*/}"
		[[ "$name" == 'TEMPLATE.md' ]] && continue
		title="$(sed -n '1{s/^# //; p;}' "$file")"
		printf '| [%s](%s/%s) | %s |\n' "$name" "$kind" "$name" "${title:-$name}"
	done
}

# Stable facts only (name, purpose, origin URL): volatile state such as the
# current branch belongs in `project-status`, not in a checked index. The
# purpose comes from the hand-maintained docs/repos.md ("- <name>: <purpose>")
# so cloned repositories never need their own files edited; a repository
# without an entry falls back to its README's first prose line, then its
# title, then the directory name.
write_repo_rows() {
	local dir="$root/repos" path name purpose title description origin
	shopt -s nullglob
	for path in "$dir"/*/; do
		path="${path%/}"
		name="${path##*/}"
		purpose=''
		if [[ -f "$docs/repos.md" ]]; then
			purpose="$(sed -n "s/^- $name: //p" "$docs/repos.md" | sed -n 1p)"
		fi
		title=''
		description=''
		if [[ -z "$purpose" && -f "$path/README.md" ]]; then
			title="$(sed -n '/^# /{s/^# //; p; q;}' "$path/README.md")"
			description="$(awk '/^#/ { next } NF { print; exit }' "$path/README.md")"
		fi
		origin="$(git -C "$path" config --get remote.origin.url 2>/dev/null || true)"
		printf '| [%s](../repos/%s/) | %s | %s |\n' "$name" "$name" "${purpose:-${description:-${title:-$name}}}" "${origin:--}"
	done
}

tmp="$(mktemp "$docs/.INDEX.md.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
	printf '# Documentation index\n\n'
	printf 'Generated by `%s`; do not edit this file by hand.\n\n' "$self"
	printf '## Operating guides\n\n'
	if [[ -f "$docs/WORKFLOW.md" ]]; then
		printf '%s\n' '- [Master workflow](WORKFLOW.md)'
	fi
	if [[ -f "$docs/locks.md" ]]; then
		printf '%s\n' '- [Exclusive resource leases](locks.md)'
	fi
	printf '\n'
	printf '## Roadmap\n\n'
	if [[ -f "$docs/ROADMAP.md" ]]; then
		printf '[ROADMAP.md](ROADMAP.md) is the project navigation view.\n\n'
	else
		printf 'No roadmap yet. Create `docs/ROADMAP.md` from the workflow template.\n\n'
	fi
	printf '## PRDs\n\n'
	printf '| PRD | Title | Status |\n| --- | --- | --- |\n'
	write_rows "$docs/prds" 'prds'
	printf '\n## ADRs\n\n'
	printf '| ADR | Decision | Status |\n| --- | --- | --- |\n'
	write_rows "$docs/adrs" 'adrs'
	printf '\n## RFCs\n\n'
	printf '| RFC | Title | Status |\n| --- | --- | --- |\n'
	write_rows "$docs/rfcs" 'rfcs'
	printf '\n## Research\n\n'
	printf '| Note | Title | Status |\n| --- | --- | --- |\n'
	write_rows "$docs/research" 'research'
	printf '\n## Plans\n\n'
	printf '| Plan | Title |\n| --- | --- |\n'
	write_document_rows "$docs/plans" 'plans'
	printf '\n## Handovers\n\n'
	printf '| Handover | Title |\n| --- | --- |\n'
	write_document_rows "$docs/handovers" 'handovers'
	printf '\n## Review records\n\n'
	printf '| Record | Title |\n| --- | --- |\n'
	write_document_rows "$docs/reviews" 'reviews'
	printf '\n## Reports - bugs\n\n'
	printf '| Report | Title | Status |\n| --- | --- | --- |\n'
	write_report_rows "$docs/reports/bugs" 'reports/bugs'
	printf '\n## Reports - investigations\n\n'
	printf '| Report | Title | Status |\n| --- | --- | --- |\n'
	write_report_rows "$docs/reports/investigations" 'reports/investigations'
	printf '\n## Reports - postmortems\n\n'
	printf '| Report | Title | Status |\n| --- | --- | --- |\n'
	write_report_rows "$docs/reports/postmortems" 'reports/postmortems'
	printf '\n## Reusable review prompts\n\n'
	printf '| Prompt | Title |\n| --- | --- |\n'
	write_document_rows "$docs/prompts" 'prompts'
	printf '\n## Agent-rule library\n\n'
	printf '| Rule set | Title |\n| --- | --- |\n'
	write_document_rows "$docs/agent-rules" 'agent-rules'
	if [[ "$workspace" == true ]]; then
		printf '\n## Repositories\n\n'
		if [[ -f "$docs/repos.md" ]]; then
			printf 'Purposes are maintained in [repos.md](repos.md); add an entry there for each clone.\n\n'
		fi
		printf '| Repository | Purpose | Origin |\n| --- | --- | --- |\n'
		write_repo_rows
	fi
} >"$tmp"
if [[ "${1:-}" == '--check' ]]; then
	if cmp -s "$tmp" "$output"; then
		printf 'docs index is current\n'
		exit 0
	fi
	printf 'docs index is stale; run %s\n' "$self" >&2
	exit 1
fi
if [[ $# -gt 0 ]]; then
	printf 'USAGE: docs-index.sh [--check]\n' >&2
	exit 2
fi
mv "$tmp" "$output"
trap - EXIT
printf 'updated %s\n' "$output"
